services:
  database:
    image: 'postgres'
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_DB=contacts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
    volumes:
      - database_data:/var/lib/postgresql/data
volumes:
  database_data:
    driver: local
