services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contacts-db
    environment:
      POSTGRES_DB: contacts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
