name: Commit Phase

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    container: rust:latest

    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose
      - name: Install Clippy
        run: rustup component add clippy
      - name: Lint check
        run: cargo clippy -- -D clippy::pedantic -W clippy::nursery
      - name: Build
        run: cargo build --verbose

  build_and_upload:
    needs: test_and_lint
    container: rust:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build release
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: companion_connect
          path: ${{ github.workspace }}/target/release/companion_connect
