name: Commit Phase

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Build release
        run: cargo build --release

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --bins

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install sqlx-cli
        run: cargo install sqlx-cli

      - name: Create database
        run: sqlx database create
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run migrations
        run: sqlx migrate run
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Check sqlx queries are up to date
        run: cargo sqlx prepare --check -- --all-targets --all-features

      - name: Run CLI tests
        run: cargo test --test cli
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Lint check
        run: cargo clippy -- -D clippy::pedantic -W clippy::nursery

  publish:
    name: Publish Release
    if: startsWith(github.ref, 'refs/tags/v')  # Only run on version tags
    needs: [build, unit, integration, lint]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Build release binary
        run: cargo build --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/nbd-cli
          generate_release_notes: true
